[project]
name = "cost-query-pro"
version = "0.1.0"
description = "A Python application for searching, managing, and analyzing unit cost data from infrastructure projects."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }

authors = [
    { name = "Brice", email = "brice@devbybrice.com" }
]

dependencies = [
    "fastapi>=0.116.1",
    "uvicorn[standard]>=0.27",
    "sqlalchemy>=2.0",
    "pydantic>=2.0",
    "pandas>=2.2",
    "python-dotenv>=1.0",
    "python-multipart==0.0.20",
    "psycopg2-binary>=2.9",
    "jinja2>=3.1",
    "pdfplumber>=0.10",
    "tabulate>=0.9",
    "httpx>=0.28.1",
    "redis>=6.2.0",
    "alembic>=1.16.4",
    "pydantic-settings>=2.10.1",
    "passlib[bcrypt]>=1.7.4",
    "python-jose[cryptography]>=3.5.0",
    "pytest>=8.4.1",
    "certifi>=2025.6.15",
    "starlette>=0.46.2",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-cov>=4.0",
    "black>=24.0",
    "isort>=5.12",
    "mypy>=1.9"
]

[project.urls]
Homepage = "https://www.devbybrice.com"
Blog = "https://medium.com/@quantshift"
Repository = "https://github.com/Brice-Engineering-Projects/Cost-Query-Pro"
