"""make llm_usage.created_at NOT NULL

Revision ID: a3f5c81e7b24
Revises: c7a4e2b91d38
Create Date: 2026-07-26

The model declares ``created_at: Mapped[datetime]`` — non-Optional, therefore
NOT NULL in Base.metadata — but migration c7a4e2b91d38 created the column
nullable. `alembic check` reported the resulting drift, and the next
autogenerated revision would have silently folded a spurious modify_nullable
into whatever else it was carrying.

Beyond the drift, the constraint matters for correctness. ``created_at`` is
the window column for the Phase 2 cost controls: the per-user and global rate
limits are a COUNT over a time window, and the spend cap is a SUM over the
calendar month. A NULL never satisfies a range predicate, so a row written
without a timestamp would be silently omitted from both — under-reporting
spend and letting requests past the limit. NOT NULL is the guard that makes
those aggregates trustworthy.

Backfill is a no-op in practice: the column has carried
``server_default=now()`` since it was created, so no NULL row can exist. The
defensive UPDATE below costs nothing and keeps the upgrade safe against any
row inserted with an explicit NULL before this revision.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3f5c81e7b24"
down_revision: Union[str, Sequence[str], None] = "c7a4e2b91d38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("UPDATE llm_usage SET created_at = now() WHERE created_at IS NULL")
    op.alter_column(
        "llm_usage",
        "created_at",
        existing_type=sa.DateTime(),
        existing_server_default=sa.text("now()"),
        nullable=False,
    )


def downgrade() -> None:
    op.alter_column(
        "llm_usage",
        "created_at",
        existing_type=sa.DateTime(),
        existing_server_default=sa.text("now()"),
        nullable=True,
    )
