"""create llm_usage table

Revision ID: c7a4e2b91d38
Revises: 68ed7ede6930
Create Date: 2026-07-26

One row per LLM completion. Backs the Phase 2 cost-control work: the rows are
the token log, the composite index serves per-user rate-limit counts and spend
sums, and the created_at index serves the global equivalents.

Written by hand rather than autogenerated: SystemSetting, ArchivedItem, and
ArchivedProject are not imported in models/__init__.py and so are absent from
Base.metadata, which makes autogenerate liable to emit spurious DROP TABLE
statements for them.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7a4e2b91d38"
down_revision: Union[str, Sequence[str], None] = "68ed7ede6930"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "llm_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        # Nullable: a model with no pricing entry records tokens with no cost,
        # keeping "unpriced" distinguishable from "free" in spend totals.
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_llm_usage_user_id_created_at",
        "llm_usage",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_llm_usage_created_at",
        "llm_usage",
        ["created_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_llm_usage_created_at", table_name="llm_usage")
    op.drop_index("ix_llm_usage_user_id_created_at", table_name="llm_usage")
    op.drop_table("llm_usage")
